./spl $HOME/myexpos/spl/spl_progs/os_startup.spl
./spl $HOME/myexpos/spl/spl_progs/timer.spl
./spl $HOME/myexpos/spl/spl_progs/module7.spl
./spl $HOME/myexpos/spl/spl_progs/module5.spl
./spl $HOME/myexpos/spl/spl_progs/interrupt10.spl
./spl $HOME/myexpos/spl/spl_progs/interrupt7.spl
./spl $HOME/myexpos/spl/spl_progs/module0.spl
./spl $HOME/myexpos/spl/spl_progs/module4.spl
./spl $HOME/myexpos/spl/spl_progs/interrupt6.spl
./spl $HOME/myexpos/spl/spl_progs/console_interrupt.spl
./spl $HOME/myexpos/spl/spl_progs/interrupt9.spl
./spl $HOME/myexpos/spl/spl_progs/module1.spl
./spl $HOME/myexpos/spl/spl_progs/module2.spl
./spl $HOME/myexpos/spl/spl_progs/disk_interrupt.spl
