echo 1
./spl $HOME/myexpos/spl/spl_progs/os_startup.spl
echo 2
./spl $HOME/myexpos/spl/spl_progs/timer.spl
echo 3
./spl $HOME/myexpos/spl/spl_progs/module7.spl
echo 4
./spl $HOME/myexpos/spl/spl_progs/module5.spl
echo 5
./spl $HOME/myexpos/spl/spl_progs/interrupt10.spl
echo 6
./spl $HOME/myexpos/spl/spl_progs/interrupt7.spl
echo 7
./spl $HOME/myexpos/spl/spl_progs/module0.spl
echo 8
./spl $HOME/myexpos/spl/spl_progs/module4.spl
echo 9
./spl $HOME/myexpos/spl/spl_progs/interrupt6.spl
echo 10
./spl $HOME/myexpos/spl/spl_progs/console_interrupt.spl
echo 11
./spl $HOME/myexpos/spl/spl_progs/interrupt9.spl
echo 12
./spl $HOME/myexpos/spl/spl_progs/module1.spl
echo 13
./spl $HOME/myexpos/spl/spl_progs/module2.spl
echo 14
./spl $HOME/myexpos/spl/spl_progs/disk_interrupt.spl
echo 15
./spl $HOME/myexpos/spl/spl_progs/exeption_handler.spl
echo 16
./spl $HOME/myexpos/spl/spl_progs/interrupt8.spl

